### ISSUE TITLE
[preact] missing in create tauri-app v3

### ISSUE THREAD

**Issue by Apogeum12** [tauri-apps/create-tauri-app#365]
How create template project like in version 2 with preact? React is too slow, solid is faster but chart.js isn't working/support (or I can't use it), preact for now is good compromise and missing in new version...
Could you some help me? Thanks

**Comment by amrbashir** [comment]
Preact has been removed as it is not widely used in comparison to react and we don't have plans to add it back atm. For your situation you have a couple of options:
1. find a template on github and use it
2. create your own template from scratch by creating a normal preact project then [integrate tauri into it](https://tauri.app/v1/guides/getting-started/setup/integrate) (and hoepfully submit it to awesome-tauri repo afterwards)
3. use create-tauri-app@2

Read the blog bost for more info: https://tauri.app/blog/2023/03/01/create-tauri-app-version-3-released

**Comment by rschristian** [comment]
Anything we (the Preact team) can do to help support it, besides making a separate template that we host on our org? Not that NPM downloads are the most scientific of resources, but it is pretty [solidly in 4th place in framework usage](https://npmtrends.com/@angular/core-vs-preact-vs-react-vs-solid-js-vs-svelte-vs-vue), certainly beating out Solid and Svelte, so I'd hope it'd be considered popular enough to host if we were to help with the maintenance burden (and I personally would be happy to help keep it supported).

I haven't used Tauri myself, but someone reached out to me today asking if we could help support a Tauri template, so figured I'd check in here first.

**Comment by Apogeum12** [comment]
@rschristian  Thanks for your comment. In tauri i only use preact as my front. It'll be great if it has official support. I think, not only for me, but also for the other developers.

**Comment by amrbashir** [comment]
> Not that NPM downloads are the most scientific of resources, but it is pretty [solidly in 4th place in framework usage](https://npmtrends.com/@angular/core-vs-preact-vs-react-vs-solid-js-vs-svelte-vs-vue), certainly beating out Solid and Svelte, so I'd hope it'd be considered popular enough to host if we were to help with the maintenance burden (and I personally would be happy to help keep it supported).
> 

To be honest, preact is indeed popular but for some reason it seemed a little behind solid in the tauri community, maybe it was a wrong assumption by me personally, I apologize.

Anyways, since more people are interested in preact with tauri, I don't mind adding it as a template, 
@rschristian feel free to open a PR.

<sub>I hope this doesn't open a flood gate to the many JS frameworks.</sub>

**Comment by rschristian** [comment]
Certainly no reason to apologize! Solid may very well be more widely used w/ tauri, be that due to aligning interests or early evangelists.

As another maintainer, I fully understand not wanting to take on additional maintenance burden, so if you feel this isn't worth it for tauri, I think we'd be happy to host this on the Preact org instead (maybe providing a couple links in the issues/trackers to send people that way in case they go looking here). I just thought I'd ask in the off chance there was the assumption that Preact in general didn't get much use.

I don't want to guilt you into this 😅

**Comment by FabianLars** [comment]
> I hope this doesn't open a flood gate to the many JS frameworks.

We both know it will 😂 But with preact we at least don't break our "no SSR frameworks" argument. (Also, having someone willing to maintain it is a big plus...)

**Comment by amrbashir** [comment]
> I don't want to guilt you into this 😅

No, don't you worry about that, preact is a good framework and it will be a good addition to CTA.

**Comment by amrbashir** [comment]
This is now included in `create-tauri-app@3.7`
