### ISSUE TITLE
VS Code integration with Yarn/Typescript by default

### ISSUE THREAD

**Issue by tsengia** [tauri-apps/create-tauri-app#469]
Hello, recently I started a project with `create-tauri-app` and selected `yarn`, `React`, and `Typescript`. This combination led to VS Code being unable to find the modules being imported (red squiggles everywhere).

To fix this, I had to run this command and then confirmed in VS Code to switch the language server settings:
```bash
yarn dlx @yarnpkg/sdks vscode
```

I don't know how this could be integrated into the current template rendering process, but I think it could be helpful to execute on the user's behalf (it took me a about a half hour to stumble upon [this SO post](https://stackoverflow.com/questions/54954337/is-it-possible-to-use-yarn-pnp-with-typescript-vscode) that solved the issue for me).

I believe this issue would be present on any configuration that uses the Typescript flavor and a PnP based package manager (yarn and possibly pnpm?).

I tested this out and the same issue occurs with the `vue-ts` template when using Yarn as package manager.

Version info: `create-tauri-app` version 3.7.2

**Comment by amrbashir** [comment]
Can you check if the same issue happens with `create-vite`?
Because it seems like something you'd need to do for any project that uses typescript with Yarn 2+ and might be need on each new fresh installation of the dependencies, so I don't think I will be adding this to the templates.

Let me know if I am missing something and it ineeded should be handled by create-tauri-app.
